apiVersion: v1
kind: Service
metadata:
  name: login-proxy
  namespace: login-proxy
spec:
  type: LoadBalancer
  selector:
    service: login-proxy
  loadBalancerIP: <LOGIN_PROXY_IP>
  ports:
  # Required for Lets Encrypt to generate certificates.
  - name: http
    port: 80
    targetPort: 80

  # Used for interacting with the login service.
  - name: https
    port: 443
    targetPort: 443

  # Used for interacting with the login gRPC service.
  - name: grpc
    port: 444
    targetPort: 444
