version: 2.1

executors:
  docker-executor:
    docker:
      - image: keldaio/circleci-blimp
    working_directory: /go/src/github.com/kelda-inc/blimp

jobs:
  build:

    executor: docker-executor

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: make

  push-docker-tagged:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Push Docker image
          command: |
            docker login gcr.io --username _json_key --password "${DOCKER_KEY}"
            BLIMP_DOCKER_REPO=gcr.io/kelda-blimp VERSION=${CIRCLE_TAG} make push-docker

workflows:
  version: 2

  pr:
    jobs:
      - build

  build-push-tag:
    jobs:
      - build:
          filters: # Required since `push-docker-tag` depends on `build`.
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - push-docker-tagged:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
