version: 2.1

executors:
  docker-executor:
    docker:
      - image: keldaio/circleci-blimp
    working_directory: /go/src/github.com/kelda-inc/blimp

jobs:
  build:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Test
          command: make test
      - run:
          name: Build
          command: make

  push-docker-tagged:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker image
          command: |
            docker login gcr.io --username _json_key --password "${DOCKER_KEY}"
            BLIMP_DOCKER_REPO=gcr.io/kelda-blimp VERSION=${CIRCLE_TAG} make push-docker

  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: golangci-lint run -v

  sync-airtable:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Sync Airtable
          command: cd ./scripts/update-funnel-airtable && go run .

workflows:
  version: 2

  pr:
    jobs:
      - build
      - lint

  build-push-tag:
    jobs:
      - build:
          filters: # Required since `push-docker-tag` depends on `build`.
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - push-docker-tagged:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

  sync-airtable:
    triggers:
      - schedule:
          cron: "0 */12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sync-airtable
