version: 2.1

executors:
  docker-executor:
    docker:
      - image: keldaio/circleci-blimp
    working_directory: /go/src/github.com/kelda-inc/blimp

jobs:
  build:

    executor: docker-executor

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: make

workflows:
  version: 2

  pr:
    jobs:
      - build
