apiVersion: v1
kind: ConfigMap
metadata:
  namespace: registry
  name: docker-auth-conf
data:
  auth_config.yml: |
    server:
      addr: ":5001"

    token:
      issuer: "Blimp Docker Auth"
      # Use a generous token expiration (1 day) so that the token doesn't
      # expire mid-push for large images.
      expiration: 86400
      certificate: "/registry-https-cert/cert.pem"
      key: "/registry-https-cert/key.pem"

    ext_auth:
      command: "/blimp-auth"
      args: ["auth"]

    ext_authz:
      command: "/blimp-auth"
      args: ["authz"]
