apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  type: LoadBalancer
  selector:
    service: registry
  ports:
  # Required for Lets Encrypt to generate certificates.
  - name: http
    port: 80
    targetPort: 8080
  # Used for interacting with the registry, and authenticating with the registry.
  - name: https
    port: 443
    targetPort: 443
  # If running on a service that allows you to set IP addresses for load
  # balancers (e.g. GKE), you can use this:
  # loadBalancerIP: <REGISTRY_IP>
