apiVersion: v1
kind: ConfigMap
metadata:
  namespace: registry
  name: docker-auth-conf
data:
  auth_config.yml: |
    server:
      addr: ":5001"

    token:
      issuer: "Blimp Docker Auth"
      expiration: 900
      certificate: "/registry-https-cert/cert.pem"
      key: "/registry-https-cert/key.pem"

    ext_auth:
      command: "/blimp-auth"
      args: ["auth"]

    ext_authz:
      command: "/blimp-auth"
      args: ["authz"]
