apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  type: LoadBalancer
  selector:
    service: registry
  loadBalancerIP: <REGISTRY_IP>
  ports:
  # Required for Lets Encrypt to generate certificates.
  - name: http
    port: 80
    targetPort: 80

  # Used for interacting with the registry, and authenticating with the registry.
  - name: https
    port: 443
    targetPort: 443
