apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: manager
spec:
  ports:
  - name: grpc
    port: 443
    targetPort: 9000
  type: LoadBalancer
  selector:
    service: manager
  loadBalancerIP: <CLUSTER_MANAGER_IP>
