# This file defines the public service that fronts the LetsEncrypt proxy, which
# in turn routes traffic to the cluster manager's HTTP API.
apiVersion: v1
kind: Service
metadata:
  name: manager-https
  namespace: manager
spec:
  ports:
  # Required for Lets Encrypt to generate certificates.
  - name: http
    port: 80
    targetPort: 80

  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer
  selector:
    service: letsencrypt
  loadBalancerIP: <CLUSTER_MANAGER_HTTP_API_IP>
