apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: manager
spec:
  type: LoadBalancer
  selector:
    service: manager
  ports:
  - name: grpc
    port: 443
    targetPort: 9000
  # If running on a service that allows you to set IP addresses for load
  # balancers (e.g. GKE), you can use this:
  # loadBalancerIP: <CLUSTER_MANAGER_IP>
