version: '3'
services:
  web:
    build: .
    command:
      - "node"
      - "/usr/src/app/server.js"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./app:/usr/src/app/app
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
