apiVersion: v1
kind: Service
metadata:
  name: link-proxy
  namespace: link-proxy
spec:
  type: LoadBalancer
  selector:
    service: link-proxy
  loadBalancerIP: <LINK_PROXY_IP>
  ports:
  - name: https
    port: 443
    targetPort: 443
